In [1]:
from __future__ import print_function

import tensorflow as tf
try:
  tf.contrib.eager.enable_eager_execution()
  print("TF imported with eager execution!")
except ValueError:
  print("TF already imported with eager execution!")

TF imported with eager execution!


In [12]:
# Suma de vectores
# Creamos varios vectores (tensores de 1-D) todos con 6 elementos exactamente, para poder sumarlos)
# Especificamos que se trata de números enteros.
# La salida incluye el tamaño/dimensiones (shape) y el tipo de valor guardado en el vector (si son enteros, etc)

primos = tf.constant([2,3,5,7,11,13], dtype=tf.int32)
print("Números primos:", primos, "\n")

# Esto crea un vector cuyos elementos (6 en total) son todo unos (6):
unos = tf.ones([6], dtype=tf.int32)

# Sumamos los primos con el vector de unos para obtener un vector de primo+1:
unomasdelprimo = tf.add(primos, unos)
print("Primos+1:", unomasdelprimo, "\n")

#Creamos un vector de doses, esta vez con una constante:
doses = tf.constant([2,2,2,2,2,2], dtype=tf.int32)
primosDoble = primos * doses
print("Doble de primos:", primosDoble, "\n")

# Llamando al método numpy en una matriz se obtiene solo el valor del tensor como array de numpy, sin más información. Si no, se ve información de dimensiones, tipo de los elementos, etc.
print("El vector de Doble de primos pero con numpy:", primosDoble.numpy(), "\n")


Números primos: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32) 

Primos+1: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32) 

Doble de primos: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32) 

El vector de Doble de primos pero con numpy: [ 4  6 10 14 22 26] 

